version: '3.8'
services:
  col0:
    image: otel/opentelemetry-collector:0.16.0
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./cfg.yaml:/conf/collector-config.yaml
    ports:
      - "55681:55681"

  col1:
    image: otel/opentelemetry-collector:0.16.0
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./cfg.yaml:/conf/collector-config.yaml
    ports:
      - "55682:55681"
